<h1><p style="text-align: center;"> Final Term (Assignment-2)</p></h1>
<h3><p style="text-align: center;">NAME: REZUAN ISLAM </p></h3>
<h3><p style="text-align: center;">ID: 20-43691-2 </p></h3>

### Importing all necessary packages and Select the dataset directory path

In [4]:
import os
import cv2
import time
from tqdm import tqdm
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Conv2D, Dense, MaxPooling2D, Flatten, Activation, Dropout

img_size = 100
datadir =  r'G:\.Summer_22-23   10th\CVPR\Face mask detection\mask_dataset'
CATEGORIES = os.listdir(datadir)
print(CATEGORIES)


['mask_weared_incorrect', 'without_mask', 'with_mask']


### Define three empty lists to contain image data

In [8]:
x, y = [], []

def PreProcess():
    for category in CATEGORIES:
        path = os.path.join(datadir, category)
        classIndex = CATEGORIES.index(category)
        print(path)
        for imgs in tqdm(os.listdir(path)):
            img_arr = cv2.imread(os.path.join(path, imgs))
            
            # Resize the image
            resized_array = cv2.resize(img_arr, (img_size, img_size))
            cv2.imshow("images", resized_array)
            cv2.waitKey(1)
            resized_array = resized_array/255.0
            x.append(resized_array)
            y.append(classIndex)

PreProcess()
cv2.destroyAllWindows()

G:\.Summer_22-23   10th\CVPR\Face mask detection\mask_dataset\mask_weared_incorrect


  0%|          | 0/3058 [00:00<?, ?it/s]

100%|██████████| 3058/3058 [01:10<00:00, 43.31it/s]


G:\.Summer_22-23   10th\CVPR\Face mask detection\mask_dataset\without_mask


100%|██████████| 3005/3005 [01:59<00:00, 25.19it/s]


G:\.Summer_22-23   10th\CVPR\Face mask detection\mask_dataset\with_mask


100%|██████████| 3126/3126 [02:03<00:00, 25.26it/s]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

### Convert and resize the data to a numpy array

In [ ]:
X_train = np.array(X_train).reshape(-1, img_size, img_size, 3)
y_train = np.array(y_train)
X_test = np.array(X_test).reshape(-1, img_size, img_size, 3)
y_test = np.array(y_test)

batch_size = 32
epochs = 15

### Create the model architecture

In [ ]:
model = Sequential()

model.add(Conv2D(64, (3, 3), input_shape=(img_size, img_size, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(128, (3, 3)))
model.add(Activation('relu'))
model.add(Dropout(0.25))

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(100, activation='relu'))
model.add(Dense(16, activation='relu'))

model.add(Dense(len(CATEGORIES)))  # Output layer with the number of categories
model.add(Activation('softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])    # Compile the model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 98, 98, 64)        1792      
                                                                 
 activation (Activation)     (None, 98, 98, 64)        0         
                                                                 
 max_pooling2d (MaxPooling2  (None, 49, 49, 64)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 47, 47, 256)       147712    
                                                                 
 activation_1 (Activation)   (None, 47, 47, 256)       0         
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 23, 23, 256)       0         
 g2D)                                                   

### Fit the model

In [ ]:
t1 = time.time()

model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.3, verbose=1)
model.save('{}.h5'.format("model"))

t2 = time.time()
print('Time taken: ', t2 - t1)

Epoch 1/15
161/161 [==============================] - 176s 1s/step - loss: 0.5814 - accuracy: 0.7432 - val_loss: 0.3731 - val_accuracy: 0.8685
Epoch 2/15
161/161 [==============================] - 170s 1s/step - loss: 0.2916 - accuracy: 0.8960 - val_loss: 0.3008 - val_accuracy: 0.8976
Epoch 3/15
161/161 [==============================] - 170s 1s/step - loss: 0.2405 - accuracy: 0.9168 - val_loss: 0.2520 - val_accuracy: 0.9075
Epoch 4/15
161/161 [==============================] - 173s 1s/step - loss: 0.2258 - accuracy: 0.9223 - val_loss: 0.1823 - val_accuracy: 0.9388
Epoch 5/15
161/161 [==============================] - 181s 1s/step - loss: 0.1780 - accuracy: 0.9399 - val_loss: 0.1915 - val_accuracy: 0.9429
Epoch 6/15
161/161 [==============================] - 172s 1s/step - loss: 0.1497 - accuracy: 0.9522 - val_loss: 0.1779 - val_accuracy: 0.9424
Epoch 7/15
161/161 [==============================] - 170s 1s/step - loss: 0.1435 - accuracy: 0.9547 - val_loss: 0.1441 - val_accuracy: 0.9565

c:\Users\rezua\anaconda3\envs\cvpr\Lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


Time taken:  2568.6997203826904


### Validation loss and accuracy

In [ ]:
validation_loss, validation_accuracy = model.evaluate(X_test, y_test)

58/58 [==============================] - 14s 248ms/step - loss: 0.0961 - accuracy: 0.9641


In [ ]:
import cv2
import mediapipe as mp
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model

### Load the model and Detection function

In [9]:
model = load_model('model.h5')

# Define mediapipe Face detector
face_detection = mp.solutions.face_detection.FaceDetection()

# Detection function
def get_detection(frame):
    height, width, channel = frame.shape
    # Convert frame BGR to RGB colorspace
    imgRGB = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    # Detect results from the frame
    result = face_detection.process(imgRGB)
    try:
        for count, detection in enumerate(result.detections):
            # Extract bounding box information 
            box = detection.location_data.relative_bounding_box
            x, y, w, h = int(box.xmin*width), int(box.ymin * height), int(box.width*width), int(box.height*height)
    except:
        pass
    return x, y, w, h

# Define the categories
CATEGORIES = ['mask_weared_incorrect', 'without_mask', 'with_mask']

# Capture video from the default camera
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        print("Failed to capture frame")
      
        cap.release()
        cap = cv2.VideoCapture(0)
        continue 
    
    img = frame.copy()
    try:
        x, y, w, h = get_detection(frame)
    except Exception as e:
        print("Error during face detection:", str(e))
        x, y, w, h = 0, 0, 0, 0  
    
    try:
        # Crop the image and do the prediction only when face detection succeeds
        if w > 0 and h > 0:
            crop_img = img[y:y+h, x:x+w]
            crop_img = cv2.resize(crop_img, (100, 100))
            crop_img = np.expand_dims(crop_img, axis=0)
            
            # Get the prediction from the model
            prediction = model.predict(crop_img)
            print(prediction)
            index = np.argmax(prediction)
            res = CATEGORIES[index]
            # Set color based on the prediction
            if index == 0:
                color = (0, 0, 255)  # Red for 'mask_weared_incorrect'
            elif index == 1:
                color = (0, 255, 0)  # Green for 'without_mask'
            else:
                color = (255, 0, 0)  # Blue for 'with_mask'
            cv2.rectangle(frame, (x, y), (x+w, y+h), color, 2)
            cv2.putText(frame, res, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.8, color, 2, cv2.LINE_AA)
    except Exception as e:
        print("Error during image processing:", str(e))
        pass
    
    cv2.imshow("frame", frame)
    if cv2.waitKey(1) == ord('q'):
        break

# Release the camera and destroy any OpenCV windows
cap.release()
cv2.destroyAllWindows()

1/1 [==============================] - 3s 3s/step
[[0. 0. 1.]]
1/1 [==============================] - 0s 71ms/step
[[0. 0. 1.]]
1/1 [==============================] - 0s 50ms/step
[[0. 0. 1.]]
1/1 [==============================] - 0s 48ms/step
[[0. 0. 1.]]
1/1 [==============================] - 0s 60ms/step
[[0. 0. 1.]]
1/1 [==============================] - 0s 41ms/step
[[0. 0. 1.]]
1/1 [==============================] - 0s 46ms/step
[[0. 0. 1.]]
1/1 [==============================] - 0s 53ms/step
[[0. 0. 1.]]
1/1 [==============================] - 0s 57ms/step
[[0. 0. 1.]]
1/1 [==============================] - 0s 40ms/step
[[0. 0. 1.]]
1/1 [==============================] - 0s 50ms/step
[[0. 0. 1.]]
1/1 [==============================] - 0s 54ms/step
[[0. 0. 1.]]
1/1 [==============================] - 0s 53ms/step
[[0. 0. 1.]]
1/1 [==============================] - 0s 76ms/step
[[0. 0. 1.]]
1/1 [==============================] - 0s 46ms/step
[[0. 0. 1.]]
1/1 [======================